### ISSUE TITLE
MySQL type 'decimal unsigned' is not being recognised

### ISSUE THREAD

**Issue by fhorlaville** [nextreports/nextreports-designer#2]
Hi again,
The MySQL type 'decimal unsigned' is not being recognised in NextReports. I suggest adding it to file nextreports-engine/src/ro/nextreports/engine/querybuilder/sql/dialect/MySQLDialect.java on line 46.

Thanks a lot,

Franck Horlaville
Senior Systems Engineer
Prism-DM

**Comment by decebals** [comment]
Done
