### ISSUE TITLE
Postgres jdbc type

### ISSUE THREAD

**Issue by Asp3ctus** [nextreports/nextreports-designer#4]
Hi
I have run in a problem to use postrges with next reports.

If i use json or serial type columns i get this type of error:

ro.nextreports.engine.querybuilder.sql.dialect.DialectException: Cannot match the type 'json' to a jdbc type

or 
ro.nextreports.engine.querybuilder.sql.dialect.DialectException: Cannot match the type 'serial' to a jdbc type

**Comment by dpmihai** [comment]
Map json, serial, bigserial data types

**Comment by Asp3ctus** [comment]
is it fixed ?

**Comment by dpmihai** [comment]
yes. it is inside nextreports-engine.
